### PR TITLE
p2pLP support

### PR DESCRIPTION
**Pull request by Gnaget**
Just added some testing support for p2pLP.  It integrates with IRC and announces new blocks.  When I figure out the best way to decide on a server, it'll select the block owner

### CODE REVIEW

**Comment by Gnaget** [comment]
oh yeah, and all code is public domain :)

**Comment by c00w** [comment]
This is awesome but 2 issues. 
1. This irc library isn't asynchronous. So watchout.
2. I can't accept the irc library because of its licensing terms. We aren't a GPL license.

**Comment by Gnaget** [comment]
I'm not familiar with GPL license terms, but can't it be used as long as the source is provided?

**Comment by Gnaget** [comment]
If not, what would you suggest?

**Comment by c00w** [comment]
Yeah. I misread it. Its LGPL so we are fine.

**Pull request merged**
