### PR TITLE
Did some cleanup since 77c462709129376c2f25

### PR DESCRIPTION
**Pull request by sdogi**
Trying again... ignore the earlier commits and only the new ones. I don't know how to remove commit so that it wouldn't appear.. github is really annoying :(

### CODE REVIEW

**Comment by sdogi** [comment]
Ok it is somewhat better now.. I still have no idea how to delete commit 75e37b2. But that is the one you should ignore. You can add in everything else because it won't break anything and does cleanup do your latest code.

**Comment by sdogi** [comment]
Ok it should all be all fine now.. I deleted my repository, downloaded your latest.. then applied my patches, commited, pushed and this pull request magically updated itself

**Comment by c00w** [comment]
Oh and I assumed this was in the public domain. If it wasn't tell me.

**Comment by sdogi** [comment]
It is yup

**Comment by sdogi** [comment]
In the future too ;)

**Pull request merged**
