### PR TITLE
minor cosmetic updates

### PR DESCRIPTION
**Pull request by ryouiki**
All of the code modifications attached to this Pull Request has been dedicated to the public domain by the author(ryouiki). Anyone is free to copy, modify, publish, use, compile, sell, or distribute without notification.

### CODE REVIEW

**Comment by c00w** [comment]
Do you either release the code under public domain or give me the copyright? Makes it so I can switch the license to something more server friendly if needed.

**Comment by c00w** [comment]
I meant into the public domain.

**Comment by ryouiki** [comment]
just edited discription.
if there is more things to do for me, feel free to let me know :)

**Comment by c00w** [comment]
http://en.wikipedia.org/wiki/Public_domain

Its not a license. It means you release it into the public domain and give up all copyright over it. I know I'm being picky but I really don't want to have legal troubles when I relicense the code.

**Comment by ryouiki** [comment]
updated description again
being new to github, I have no idea how to release pull request as public domain form.
if it is not enough, or more formal term is needed, let me know.

**Comment by c00w** [comment]
I'm going to be trying to merge this sucker. Um I already disabled btcguild however. Lets see what I can do.

**Comment by c00w** [comment]
Hmm. It won't let me auto merge it. I'm going to leave this till tommorow and see if I can figure out a way to get this merged. I'm rewriting bitHopper as we speak so this should be an interesting exercise.

**Comment by c00w** [comment]
Well I did the cleanup when I was rebuilding pool.py. I'll add the better rpc stuff for non debug mode. I'm not sure if the stats stuff is a great idea since format is borked for python 2.6...

**Comment by ryouiki** [comment]
nice work. i'll close this request

**Pull request closed without merging**
