### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by paraipan**
Path and script/exe detection proposed by sukrim

### CODE REVIEW

**Comment by c00w** [comment]
Is this released into the public domain or copyright transferred to me?

**Comment by paraipan** [comment]
dunno I will ask sukrim

**Comment by c00w** [comment]
Oh and each of these needs a final else block to do the default with os.curdir, and some of these cases won't work, but I can just fix it pretty quickly.

**Comment by paraipan** [comment]
you rock man, I understand little about coding, sukrim and I would learn from you hehe

**Comment by paraipan** [comment]
closed

**Comment by c00w** [comment]
Is sukrim going to make a pull request? Like i would love to just distribute a py2exe version and this makes it a lot simpler.

**Comment by paraipan** [comment]
I hope so, seems I copy pasted like shit so it will be better for sukrim to make his own pull req

**Pull request closed without merging**
