### PR TITLE
Skins!

### PR DESCRIPTION
**Pull request by macboy80**
Adds StatSkin directory and includes pool.cfg clean-up and very minor changes to default. (Check them out first)  All index up to date with newest features. Very proud of "Sentient" scheme.

EDIT: Also set to display local time for last seen.

### CODE REVIEW

**Comment by c00w** [comment]
Wow... I definetly need to rewrite the code to make this a heck of a lot more versatile with regards to websites... Because honestly this patch makes if functionally imposible to do anything to any website easily. Is there a way for you to isolate the color changes into an included javascript file or something? Then we could just swap those at the command line.

**Comment by macboy80** [comment]
I would love to do something like that. I'm not sure I know how to do that, though. I'll try to figure something out if i can, and regardless I would definitely contribute to whatever the framework becomes. In the meantime, I figured it was best to share. Your call whether to pull, but I'll try to keep them up to date with whatever changes you make to the default.

It does seem like it may be time to combine the index's into one (index-slice would have every feature). The only real discrepancy would be the OldDefault/macboy index would show dashes in the slice column. That would make it much easier to integrate changes across the skins. A command line argument could select the appropriate index either by file name or by directory ie: --StatusPage sentient; --StatusPage flower; etc.

**Comment by c00w** [comment]
Yeah. I'll merge all of the index's into one and then we can figure out what to do with the skin changes.

**Comment by c00w** [comment]
I removed all of the extra index.html pages.
This might be of interest to you:
http://www.digitalbonsai.com/change_css.php

**Pull request merged**
