### PR TITLE
Added bitcoinpool.com support

### PR DESCRIPTION
**Pull request by echiu64**

### CODE REVIEW

**Comment by c00w** [comment]
HI, I didn't see that this was a dup of the other one and responded there but I just wanted to say that bitcoinpool is a dangerous pool to hop. However I am happy to merge it in and set it to info mode for those who want to take the risk.

I just need you to either give me the copyright or release it into the public domain so that I don't have to worry about relicensing issues.

**Comment by echiu64** [comment]
Sure no problem, not sure how to give you copyright release, i'm assuming my changes fall under the same license, since i haven't changed the license or attribution?

**Comment by c00w** [comment]
Just say in a comment that you release the work into the public domain. It basically means anyone can use the code.

**Comment by c00w** [comment]
Per your comment in the other thread about ditching them due to faked shares, I don't really care. getting the info is quite useful. Even if they fake shares having some real shares could be useful when we try and solve the deepbit problem. I'd still like to merge this.

**Comment by echiu64** [comment]
Releasing this commit to public domain, feel free to reuse, redistribute, etc.

Evidence of stats faking:

bitcoinpool-graph

**Comment by c00w** [comment]
... Thats not even trying to do it well.

**Comment by Clipseza** [comment]
This brings into effect them stealing blocks.

They are currently paying out just about as much as they are faking their stats, great con job.

**Comment by c00w** [comment]
According to those stats they are incredibly lucky...

**Pull request merged**
