### PR TITLE
"Fix" for MTRed not pulling hashrate and shares info.

### PR DESCRIPTION
**Pull request by HolodeckJizzmopper**
MTRed was not properly reporting stats in the 2.5.5. download

### CODE REVIEW

**Comment by c00w** [comment]
Is this in the public domain and did you have mtred_user_apikey set?

**Comment by HolodeckJizzmopper** [comment]
What do you mean "Public Domain" ? And yes, I had my user key set, but it didn't show that information under my user settings.

**Comment by c00w** [comment]
At some point I want to relicense all of bitHopper to something less bizarre and silly than Creative Commons. If the work in it is not in the public domain or I don't have control of the copyright I can't make that change.

**Comment by HolodeckJizzmopper** [comment]
I'm not about to claim ownership of me diddling a few lines in a cfg file.

 If this fixes an issue for someone, it's yours.

**Pull request merged**
