### PR TITLE
Added AltSliceScheduler

### PR DESCRIPTION
**Pull request by echiu64**
Weighted Time based slicer, only minimal change to other class to mark if stats initialized or not. Minimal testing / simulation done. Will test over next 24h

### CODE REVIEW

**Comment by c00w** [comment]
Public Domain / transfer copyright to me?

**Comment by echiu64** [comment]
Yes public domain

**Comment by echiu64** [comment]
Ya, it's a little screwy, seemed ok when only 2 pools were hoppable. Right now with many pools, it seems to prematurely reslice... i'll have to take a look. Good thing it's isolated :)

**Comment by echiu64** [comment]
Will send the latest

**Pull request closed without merging**
