### PR TITLE
mine_friendly

### PR DESCRIPTION
**Pull request by Gnaget**
added a role "mine_friendly" with the behavior that when there are no pools to hop, it searches first for the hopper friendly pool with the most shares and at least 200% of difficulty.  If found, it mines, else it moves on to the backup pools

### CODE REVIEW

**Comment by c00w** [comment]
Do you release the code into the public domain or transfer the copyright to me?

**Comment by Gnaget** [comment]
of course, I wrote it specifically for you :)

public domain.. yadda yadda

**Comment by Gnaget** [comment]
cancel this, I am running it on my server now, and something caused it to stop mining...  looking into it

**Comment by Gnaget** [comment]
ok, so you don't need my fix?  I should have run it on my server longer, I was testing it on a single card, and not long enough for the issue to pop up :/

**Comment by c00w** [comment]
If there are bugs I need fixes. But base it off of the trunk instead of your branch because I got impatient and merged the earlier version. It looks like I did all of the same things as you however.

**Comment by Gnaget** [comment]
ok, forgive my ignorance of this source control, I'm not a git user.  How do I merge in your changes?

**Comment by c00w** [comment]
http://help.github.com/send-pull-requests/
See section on merging pull requests.

**Comment by c00w** [comment]
$ git checkout master
$ git remote add c00w git://github.com/c00w/bithopper.git
$ git fetch c00w
$ git merge c00w/master
$ git push origin master

**Comment by c00w** [comment]
I screwed up my merge message but this has been merged in.

**Pull request closed without merging**
