### PR TITLE
Minor enhancements / documentation

### PR DESCRIPTION
**Pull request by echiu64**

### CODE REVIEW

**Comment by c00w** [comment]
Public Domain?

**Comment by echiu64** [comment]
Released to public domain

**Comment by echiu64** [comment]
Added a fix for proper blockid, not sure if this got corrupted in a previous merge, looks like there was some bad indentation on one of the methods as well

**Comment by c00w** [comment]
Good catch with the word reverse. Does this commit actually extract previous block hashes correctly? The previous one didn't and picked up part of the merkle root which is server specific.

**Comment by c00w** [comment]
Tested and it works.

**Pull request merged**
