### PR TITLE
Add slice data to HTML page (configurable by scheduler)

### PR DESCRIPTION
**Pull request by echiu64**
Small change. Tested with Chrome stable, using default & slice scheduler

### CODE REVIEW

**Comment by paraipan** [comment]
hy echiu64, would you mind giving some advice how to test this ? nice idea btw

**Comment by c00w** [comment]
Public domain or transfer the copyright to me?

**Comment by echiu64** [comment]
c00w: yes public domain, feel free to reuse
paraipanakos: just load the stats page when using the slice scheduler and you should see the slice column, i believe it shows the number of seconds that particular pool has been used

**Comment by paraipan** [comment]
thanks testing it now

**Pull request merged**
