### PR TITLE
Fixed coinotron rate duration api method  

### PR DESCRIPTION
**Pull request by Locky7**
public domain

### CODE REVIEW

**Comment by itstooez** [comment]
Now that the "m" is not being displayed by Coinotron, the above pull is showing the round duration of IXC.

api_key_duration_hour_min: BTC._\s._\s._\s._>([0-9]+) h ?([0-9]+)? ?m?</td>

^ Fixed.

**Comment by Locky7** [comment]
api_key_duration_hour_min: BTC.\s.\s.\s.>([0-9]+) h ?([0-9]+)? ?m? works for you?  

Removing the m broke it before, so it must be intentional...  

Does the api method need to approximate m?

**Comment by itstooez** [comment]
That's what the ?'s are for, the character before is option.  When coinotron hits their 12 hour mark, or whatever, and removes the "m"...bitHopper will search, but return NoneType I believe...which is then 0 for bitHopper.

api_method: re_rateduration
api_key_ghashrate: ([ 0-9]+).([ 0-9]+) GH</td>
api_key_duration_hour_min: BTC._\s._\s._\s._>([0-9]+) h ?([0-9]+)? ?m?</td>
api_strip: ''

The above code works for me.

Coinotron   547,337 50.18%      *18h:0m

**Comment by Locky7** [comment]
I am getting 4,536,000 415.87% and no round time display?

**Pull request merged**
