### PR TITLE
Update

### PR DESCRIPTION
**Pull request by paraipan**
Added kiwipool, thanks user7516
New pool section in user.cfg.default en+esp
Merged updates from upstream

### CODE REVIEW

**Comment by c00w** [comment]
Public Domain / Transfer copyright to me? And you missed a conflict in user.cfg.default.

**Comment by paraipan** [comment]
rights to you, sorry about the conflict tell me where and I'l fix it, if you get the LP stuff going you're my hero c00w

**Comment by c00w** [comment]
user.cfg.default:187

Just do a search for ======

**Comment by paraipan** [comment]
opps sorry, it was nasty

**Pull request merged**
