### PR TITLE
Fixes for btcnet_info submodule download code

### PR DESCRIPTION
**Pull request by elitak**
Notes on my changes:
- Now checks for the presence of the module before trying to install it, for those that want to use git-submodule.
- If people want to update the module, they should just delete the subdir and restart. It shouldn't be downloaded every time.

Unaddressed Grievances:
- Comments describing what is going on in magical import routines would be nice.
- Why sys.exit(2)? Where's exit code 1?
- What does .zip represent? The "true" content is uninformative, not to mention unused; the file may as well be empty. It's created by pull_zip and used by pull_zip to preempt git, which is very bad semantics, IMO.

### CODE REVIEW

**Comment by c00w** [comment]
This code is an ugly ugly hack which I dislike immensely. However it seems to be the only way to make sure that people who download in zip, git etc... get btcnet_info pulled. Also we'd like it to update automatically if there is a new version.

**Comment by c00w** [comment]
@elitak 
sys.exit(2) is because 1 is success and I wanted to report an error code.
I'll add some comments. Mea Culpa
.zip represents the fact that we had to fallback to zip download mode. If git downloads fail then we should fallback to zip downloads and since that messes up the git structure we're basically stuck using zip from now on.

**Comment by elitak** [comment]
- "success" should always be error code 0.
- Ideally, everyone would use git to properly sync their installation. Seeing as that's unlikely, maybe the better approach would be for them to download and run an installer that's maintained in a separate repository like "bitHopper-installer". That way, you'd separate the runtimes and concerns of installation and execution. Users would download the bitHopper-installer.zip, run something in there, then startup bitHopper from whatever the installer had fetched.
- (This point is moot if you switch to the approach suggested above) The presence of ".zip" causes the package to be redownloaded every startup. I don't know if that was your intent, but it seems excessive and potentially problematic for reasons I've detailed below.

<div>
I just noticed that neither method pulls correctly. Each bitHopper commit is bound to a certain commit of btcnet_info. If the two diverge uncontrollably, you may end up with incompatibilities. That's what both pull_ methods are doing now: they're pulling HEAD instead of the commit specified in `git submodule`. The correct behavior is to use the equivalent of 'git submodule update' or to fetch a zip that's synced to the correct HEAD found in `git submodule` -- I don't know if github allows that, but I imagine they should. Consider passing `git submodule | awk '{print $1}'` (but prettier, using python-git) to both pull_() functions.
</div>


(Edits: markdown was interpreting my backticks and such incorrectly)

**Comment by c00w** [comment]
The issue is that not everyone installs bitHopper using git. A lot of people just go to the download page on github and click the zip button. Thus there is no submodule and no idea what commit should be pulled.

Another issue is that people wanted to have their pool information autoupdated. What we are trying to do is to have btcnet_info always be the latest version. However git submodule does not really support that thus why we are trying to pull the HEAD commit instead of what is actually tagged.

**Comment by c00w** [comment]
I like the idea of an installer and I'm trying to set one up using pip. The crucial issue is waiting for gevent to be bundled properly once they release 1.0 I'll probably set it up and release it.

**Pull request merged**
