### PR TITLE
New plugins, small changes

### PR DESCRIPTION
**Pull request by echiu64**
Added in various hooks
Refactor apiangel plugin (nicer in editors if you don't have lots of **init**.py files open)
Added poolblocks plugin which will enable future plugins by having a data structure that contains known blocks from various blooks:
- verifying block guessing accuracy

### CODE REVIEW

**Comment by c00w** [comment]
Is the copyright for everything which is not licensed separately either transferred to me or is it in the public domain?

**Comment by echiu64** [comment]
Released to public domain

**Comment by echiu64** [comment]
Shoot, one thing we should do is disable it by default, since it's only usable if something else uses it's data, which is currently nothing

**Comment by echiu64** [comment]
I also left in a "print" statement in by mistake around like 176 i think, will send another pull tonight

**Comment by c00w** [comment]
I fixed the print statement around line 176.

**Pull request merged**
