### PR TITLE
Stats page appearance improvements

### PR DESCRIPTION
**Pull request by macboy80**
These commits include:
Color scheme and layout changes to stats page
Changes to both the pool.cfg and user.cfg.default to capitalize server names on stats page.

EDIT: My changes / code are public domain or whatever is easiest for you.
EDIT 2: Only pool.cfg has been changed to capitalize stats page name. Internal names remain the same.

### CODE REVIEW

**Comment by rkozola** [comment]
changing those server names is going to mess up everyone's stats.db

**Comment by macboy80** [comment]
It does look WAY better, though. Definitely worth it. Those changes are in a separate commit, so it can be left out if that is the community's will.

**Comment by c00w** [comment]
This is going to be annoying to merge. Honestly we can't just change server names like that without messing up the db.

**Comment by macboy80** [comment]
That's fine with me. I haven't been keeping stats.db between builds, so I wasn't aware it was an issue until the feedback. I do have one question. Is it the server heading as in "[slush]" or the name entry as in "name: slush" or both that messes up the db? I just figured out that the heading doesn't show on the stats page.

**Comment by paraipan** [comment]
pushed you a fix macboy80, user.cfg.default changed a little bit though. You should make pull request to c00w of "index.html" and "pool.cfg" or "pools.cfg" only if you want it in mainstream version

**Comment by c00w** [comment]
The heading is what the database uses. Set name to whatever you think looks best because that is what the website uses.

**Comment by macboy80** [comment]
@c00w - I merged paraipanakos changes for the pool.cfg. I am at work right now, so I can't change user.cfg.default. Can you just ignore it in the merge? Otherwise, I will change when I get home.

**Comment by c00w** [comment]
Yeah. I can do the merge. Thats not a problem. I'm just holding off on it b/c I want to get some food and relax a little and do some work for my actual job.

**Comment by paraipan** [comment]
I'm on vacation yupee

**Comment by macboy80** [comment]
@c00w: I know the feeling. My boss is giving me dirty looks right now. Take your time.
@paraipanakos: Way to rub it in. Thanks for the changes.

**Comment by paraipan** [comment]
hahahaha, np macboy liked your stats page :)

**Comment by macboy80** [comment]
Got a quick request. Can you guys give me a recommendation over at "the den"? I haven't been verified yet. :(

**Comment by paraipan** [comment]
open a thread in General and you should get verified in no time

**Comment by macboy80** [comment]
It's been there since 7/29... no replies.

**Comment by paraipan** [comment]
sorry about that, I think forum has an issue reporting new post and threads, hope you get active soon

**Comment by c00w** [comment]
Dang. I really need to merge this pull request.

**Comment by paraipan** [comment]
The stats page it's really cool :) I'm sure macboy80 would change thing ppl don't like

**Pull request merged**
