### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by paraipan**
Changed polmine info, added oldpolmine re
Changed bclc info

### CODE REVIEW

**Comment by simonk83** [comment]
Ok, so the polmine info was changed to scrape the share count from the stats page.  Just now polmine reset so I kept my eye on it.   The shares on the stats page showed 7688, whilst on the user stats page it showed 1.5million odd.   Then, the shares on the stats page completely disappeared.

I'm not sure if they removed it because we were scraping it, or just because it was wrong.

How about altering the api regex to scrape the share count from the user stats page?

https://polmine.pl/?action=dashboardstat

prediction  prediction  ( 1554 / 1616211) \* 50.02285080 0,04809738  2011-08-10 13:51:48

In the above example, 1616211 is the current share count (as this is what they're using to estimate the reward).

Don't forget it needs to be scraped in polish though, not English ;)

**Comment by paraipan** [comment]
would be nice but python-twisted doesn't seem to have the ability to log in and view the dashboard, see where I'm getting to ? the info has to be public

**Comment by simonk83** [comment]
Aaaaah, of course. Thought it sounded a bit too easy ;)

**Comment by c00w** [comment]
Um you can use whatever library you want for the scraping.

**Pull request merged**
