### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by paraipan**
Update btcpool24 url:
Added btcguild api re_rate, by jkminkov
Changed polmine role in user.cfg.def esp
Fix itzod api address
Added swepool to user.cfg.def esp (moved to new in cfg en)

### CODE REVIEW

**Comment by c00w** [comment]
Hmmm. In the long run this will actually help results we just don't use it currently... So I'm not sure what to do.

**Comment by paraipan** [comment]
you know better c00w, atm the small pools spamming LP's were just standing in deepbit's way, you could put them on info I guess when we troubleshoot more the LP system, really didn't liked getting all that LP spam

**Comment by paraipan** [comment]
or we could enable the one by one and troubleshoot :)

**Comment by paraipan** [comment]
guess it works with all pools enabled or on info

**Comment by c00w** [comment]
Public Domain or Transfer Copyright to me?

**Comment by paraipan** [comment]
copyright to you c00w

**Pull request merged**
