### PR TITLE
some new updates

### PR DESCRIPTION
**Pull request by Gnaget**
All servers now update stats unless role=='disable'
api_disable will keep updating, and will change back to mine when new data is found
changed sorting, makes more sense for mine to be first

released to the public domain and all

### CODE REVIEW

**Comment by Gnaget** [comment]
found an issue with mine_friendly servers, they weren't being selected for new blocks.  fix is included

**Comment by c00w** [comment]
Um.. I already fixed the first issue and well there are no stats for backup pools. I'll apply the second commit.

**Comment by c00w** [comment]
Um actually I might not have fixed the first issue but the second commit doesn't seem to match the current trunk.

**Comment by Gnaget** [comment]
You can't merge?  Looks like you made quite a few changes between the time I worked on this, and you got to my pull request.

**Pull request merged**
