### PR TITLE
Reduce traffic to unhopped pools, add abcpool

### PR DESCRIPTION
**Pull request by pueytan**
Throttle share scrapes for info, backup, and backup_latehop roles to once per hour to reduce load on pools
Add api_method: disable to avoid error messages when not scraping shares.
Add ABCPool for testing purposes.

### CODE REVIEW

**Comment by c00w** [comment]
Public Domain? And can you confirm that this does not nuke the workers table?

**Comment by pueytan** [comment]
Whatever license you used for bitHopper is probably fine.
I have been running it for a while now and it works; wouldn't submit a pull request if it didn't. Why do you ask?

**Comment by pueytan** [comment]
hang on, now it broke for some reason

**Comment by pueytan** [comment]
nevermine i was being retarded by trying the url without /stat

**Comment by c00w** [comment]
Sorry I'm tired. Another pull request was supposed to get the nuke the workers table. But I think I already merged it.

**Comment by sdogi** [comment]
This now seems to have:

if (id == "#table") { .... }  so it should be fine yup :)

**Comment by sdogi** [comment]
I just hope it doesn't cause conflicts.. since I patched it by editing the same region where he added the new info pools. But should be easy to fix

**Comment by pueytan** [comment]
To be honest i don't see the difference for:
if (id == "#table") 
It worked either way, but I kept it since it was a good idea.

**Comment by sdogi** [comment]
Might be browser differences.. lot of people reported that their worker stats disappeared

**Comment by pueytan** [comment]
Alright sdogi, I think I got your feature.

**Comment by c00w** [comment]
Oh and pueytan: I really need your work to either have the copyright transferred to me or be in the public domain. I'm planning on re-licensing bitHopper at some point and don't want to have to get your permission.

**Comment by pueytan** [comment]
Sure, I can transfer them to you. Hope I can still get updates when you change your licensing.

**Pull request merged**
