### PR TITLE
Lpdynamic / blockaccuracy various fixes

### PR DESCRIPTION
**Pull request by echiu64**

### CODE REVIEW

**Comment by paraipan** [comment]
sup echiu, could you be so kind to change back displayed time for LP arrivals like it was before ? dunno if you can but i'm asking anyways :)  like it was in  your first commit showing the difference in seconds or less from the owner (LP winner), btw nice tools you got us for bH, thanks

**Comment by c00w** [comment]
Public Domain?

**Comment by echiu64** [comment]
Released to public domain

**Comment by echiu64** [comment]
paraipanakos: are you using the latest? Could be a defect i fixed? It should be display time relative to the winning LP (either LP guessed or if verified owner available, it will show that) Once verified, if there is no timing data, the display will show n/a. The data isn't useful if we don't have timings from the winning pool.

**Comment by paraipan** [comment]
yeah I was using cd52f5d and it shows up precise time in lpworkbench (like 1316351257.5473), wil pull the update in a moment, thanks

**Pull request merged**
