### PR TITLE
Various patches for new version

### PR DESCRIPTION
**Pull request by sdogi**
Had to update the pull request message because it was initially only for reverting docstring into a comment.

Anyway been going over the code today and here are various fixes I have done.. one of them makes it possible to stop bithopper again without killing it forcefully.

### CODE REVIEW

**Comment by sdogi** [comment]
After fixing this I now get this error at startup:

[04:58:54] New Block: b7a70f708e8d877cb76a8dd5bbe25eeaffc5b7ff4594a897000006c500000000
[04:58:54] Block Owner bitclockers
[04:58:54] Setting Block Owner bitclockers:b7a70f708e8d877cb76a8dd5bbe25eeaffc5b7ff4594a897000006c500000000
[04:58:54] LP Call http://pool.bitclockers.com:8332/LP
[04:58:55] LP Call http://arsbitcoin.com:8344/LP
Traceback (most recent call last):
  File "F:\data\projects\bithopper\bithopper-stable\eventlet\hubs\hub.py", line 336, in fire_timers
    timer()
  File "F:\data\projects\bithopper\bithopper-stable\eventlet\hubs\timer.py", line 56, in **call**
    cb(_args, *_kw)
  File "F:\data\projects\bithopper\bithopper-stable\eventlet\semaphore.py", line 95, in _do_acquire
    waiter.switch()
error: cannot switch to a different thread
[04:58:55] LP Call http://pit.deepbit.net:8332/listenChannel
[04:58:55] LP Call http://btcserv.net:8335/LP

But it will continue running

**Comment by c00w** [comment]
Um, thats a docstring. Not a bad comment...

**Comment by c00w** [comment]
But if we can figure out this error it would be good.

**Comment by sdogi** [comment]
Nice I was kind a suspicious why it didn't show up as a warning/error in my IDE. Never used them but I always thought docstrings require triple double-quotes.

Going to try to hunt down those issues today.

**Comment by sdogi** [comment]
Looked up docstrings for Python. Seems """ isn't required but it is convention so I changed it to make this commit useful
http://www.python.org/dev/peps/pep-0257/

**Comment by sdogi** [comment]
Still looking... seems freezing problems still persist(according to users) but they can happen from anywhere to 1-10 hours. Haven't been able to reproduce yet.

**Comment by c00w** [comment]
Um, if you want to rewrite the wrapper loop so it quits more cleanly catch and return on stopiteration exceptions. Also the reason we are getting resp which is the headers is we want to pass those back to the miner at some point. So don't drop them or we'll have to add them later.

**Comment by sdogi** [comment]
I figured you would like to get resp later, this is why I added the return blob into comment. Haven't got the stopiteration exceptions but I guess it wouldn't be very difficult to rewrite it to support double loop.

Check out the freezing issue #256 from the tracker too. I got a trace log for it, need your advise though on what to do about it

**Comment by sdogi** [comment]
Ok merged in everything and tested with clone of your latest, it didn't cause any merge conflicts. In one later merge from you I replaced my changes with wsgi wrapping loop you still use with eventlet.sleep(). It appears though that for some reason this doesn't always work. And even if it works it requires you to press ctrl+c twice.

I figured out very elegant solution for supporting double exception catching loops(one inside wsgi.server() another in bitHopper.py) though. I just added break after wsgi.server :)

Tested and works fine.

Do you want me to revert work.py cleanup for now? Because currently some variables are unused and since I figured you may or may not want to use them in the future I added a comment behind every function I cleaned up like this:

username, password = data.decode('base64').split(':', 1)
to
username = data.decode('base64').split(':', 1)[0] # Returns ['username', 'password']

It is good practice to never leave unused data lingering behind, can become nasty with huge code base.

**Pull request merged**
