### PR TITLE
Few changes...

### PR DESCRIPTION
**Pull request by paraipan**
edit: i added def lp penalty 0 for db/btcg and few other changes

### CODE REVIEW

**Comment by c00w** [comment]
Um... Don't you want the other pools to get a bonus? So -10?

**Comment by paraipan** [comment]
heh dunno, what bonus ? i just want to retard lp for all pools except db and btcg by default to get new hoppers mining them right from the start

**Comment by sdogi** [comment]
So all others except db/btcg should be preferred?

In that case c00w's remark is right indeed but I would suggest that we wouldn't use -10 for default but just set all pools to penalty 10 and deepbit/btcg to 20.

If you specify negative penalty it won't show up nice in web interface.

But when we do it the way I suggest then it's possible to tweak most pools default penalty of 10 down to zero if there would be any need for that and it would look nice. Unlike right now when I use -1 penalty for some pool and I just have to remember it because there is no difference between 1 and -1.

**Comment by paraipan** [comment]
eh are we talking a bout the same thing here ?  LP_penalty is measured in seconds, so a LP_penalty 10 would delay LP resets fro that pool 10 seconds, this is only useful for mine_deepbit pools so the ones that have good updating api get ignored when they reset LP but bH hops them correctly. This is more like a indication for new hoppers how they should set up correctly for LP hopping to work right from the start

**Comment by paraipan** [comment]
i have tested this setup for few weeks, it's more like a workaround for us setting LP preference from mine_deepbit pools but at the same time subscribe to LP to all pools and receive them with a small delay for when it's needed. GenTarking could help me explain this more accurately because he gave us the initial live results on irc.

**Comment by sdogi** [comment]
Ah yeah, I didn't even notice there is LP penalty now. Thought you were changing threshold penalty, sorry.

My ideas was to set threshold penalty default to 10.. so that it would be cleaner when changing penalty lower to get a preference of certain pool. Negative penalty threshold is hidden in web interface right now. Probably not best to do this using config file though.

**Pull request merged**
