### PR TITLE
Plugin fixes; pool.py fix for mining different coin types

### PR DESCRIPTION
**Pull request by echiu64**
Introduces util/urlutil.py, rate limited URL fetcher (useful when grabbing lots of stats for block info and blockexplorer lookups)

Commit 8953df3f fixes the issue where if a NMC pool hits, it can steal a recent LP. Added a check by coin type.

New plug blockaccuracy, default is turned off.
Will report every 10 minutes or so the accuracy of LP guessing, based on blocks we can validate off pool stat sites. Full list of pools checked are in poolblock.cfg

Updated /lpworkbench to show verified pool as well.

Some other minor changes, including coding conventions when it comes to extensions/plugins.

### CODE REVIEW

**Comment by c00w** [comment]
1. Public Domain or Transfer Copyright to me?
2. Where did you get that rate limiter code from. Did you write it yourself?
3. You can have the lp_workbench plugin just add itself to the website list outside of website.py and in the plugin startup. See the poclbm plugin.

**Comment by echiu64** [comment]
1) Released to public domain
2) Stackoverflow, http://stackoverflow.com/questions/456649/throttling-with-urllib2
UGC on stackoverflow is licensed under CC
3) So let me try this out..
- Move lpSite() to plugin, that seems doable
- Add lpWorkbench to self.sites, also doable
- How to add to dataSite()? I added an additional data element "block", perhaps I should have my own dataSite() class?

``` python
    response = json.dumps({
            "current":self.bitHopper.pool.get_current(), 
            'mhash':self.bitHopper.speed.get_rate(), 
            'difficulty':self.bitHopper.difficulty.get_difficulty(),
            'ixc_difficulty':self.bitHopper.difficulty.get_ixc_difficulty(),
            'i0c_difficulty':self.bitHopper.difficulty.get_i0c_difficulty(),
            'nmc_difficulty':self.bitHopper.difficulty.get_nmc_difficulty(),
            'scc_difficulty':self.bitHopper.difficulty.get_scc_difficulty(),
            'sliceinfo':sliceinfo,
            'block':self.bitHopper.lp.getBlocks(),
            'servers':self.bitHopper.pool.get_servers(),
            'user':self.bitHopper.data.get_users()})
```

**Comment by c00w** [comment]
We should probably add a hook and append everything which is returned from requesting that hook to be added to the data stream. But hardcoding it is fine for now.

**Comment by echiu64** [comment]
Actually i stripped out some unneeded data and made by own "data" site for now... maybe don't want to clutter the main data stream for something that won't always be open?

Moved to plugin now, commit 37102d9

**Pull request merged**
