### PR TITLE
Extract hopping logic into seperate file/class

### PR DESCRIPTION
**Pull request by echiu64**
To make it easier to add in different hopping logic

### CODE REVIEW

**Comment by c00w** [comment]
This is pretty awesome. Is the code released into the public domain or copyright transferred to me?

**Comment by echiu64** [comment]
Yes, I believe I assigned you the copyright in the source...

**Comment by c00w** [comment]
Sweet. Merging.

**Comment by c00w** [comment]
Um, so your server_update didn't actually work... I fixed it but you didn't make select_best_server directly modify pool.py, instead it returned the best server, which is probably the right way to do it.

But server_update just called select_best_server internally. So it never changed server...

**Comment by echiu64** [comment]
Thanks for the fix, had to fudge my testing a bit... working on adding in a time slice scheduler now

**Comment by c00w** [comment]
Sweet. Heads up that we now have a getwork store so you can just change where the getworks come from arbitrarily.

**Comment by echiu64** [comment]
Ah interesting, do you have an example? I'll probably merge in the slice logic as is, before trying the getwork store...

**Pull request merged**
