### PR TITLE
Added support for nofeemining.com

### PR DESCRIPTION
**Pull request by graphiclunarkid**
Hi

I added support for another small, proportional pool called nofeemining.com, and thought you might like to merge it into your code for others to use.

Cheers

/graphiclunarkid

### CODE REVIEW

**Comment by c00w** [comment]
Do you enter the code into the public domain or transfer the copyright to me? Otherwise if I accept the code I can't change the license. Ever.

**Comment by graphiclunarkid** [comment]
I hereby release the code I have written in this pull request into the public domain. Do with it what you will :)

**Comment by graphiclunarkid** [comment]
Apologies for messing up this commit with some later changes. This is the first time I've contributed to a project on GitHub and I'm not familiar with how it works yet. If you like you can close this pull request and I'll re-submit it from a branch instead to isolate the nofeemining.com support from the other stuff I was messing around with.

**Comment by graphiclunarkid** [comment]
OK I've cleaned up my mess and submitted a new pull request so I'm closing this one. Apologies for the n00b error!

**Pull request closed without merging**
