### PR TITLE
Lots of clean up, some bug fixes and multi-user support for --auth

### PR DESCRIPTION
**Pull request by sdogi**
See commit messages for more information. I fixed bunch of unused imports, variables. Also some typos and since --auth seems to be applied to workers too now I added ability to add multiple users like this:

bitHopper.py --auth user1:pass1,user2:pass2

I also added information about this to README files. Unfortunately I don't know Spanish so you might want to check the Spanish README because I just did copy & paste :)

### CODE REVIEW

**Comment by sdogi** [comment]
By the way.. these files that seem like there were some really big changes. These are indentation fixes. There were lot of places where there were either 3 spaces instead of 4 or spaces mixed with tabs. It was showing up really funky in many different editors.

**Comment by c00w** [comment]
Public Domain?

**Comment by sdogi** [comment]
Ok

**Comment by c00w** [comment]
Um... I did a bunch of cleanup as well.  So this is really annoying to merge. I'll do it when I have time.

**Comment by sdogi** [comment]
Yeah I saw. No problem. You might want to do the website.py and bitHopper.py first though since it will add multi-user support.

**Comment by c00w** [comment]
Well the issue is that I ran through most of my code with pylint last night. So merging scheduler.py is just a mess.

**Comment by sdogi** [comment]
Skip scheduler.py then.. this one was mostly indentation anyway iirc

**Comment by sdogi** [comment]
Yeah.. went over it again. I think I opened it up in Eclipse and it had all screwed up indention.

Only thing that I did there besides that was that I removed:
import os.path

Only valuable things can be found from website.py and bitHopper.py.. there were some typos I fixed too but I think you already pushed them.

**Comment by sdogi** [comment]
Closing to merge with latest and send new pull

**Pull request closed without merging**
