### PR TITLE
added div #headercontainer to stick the currently mined pool and legend t

### PR DESCRIPTION
**Pull request by hawks5999**
added div #headercontainer to stick the currently mined pool and legend to the top of the window. The pool table will now scroll without scrolling current off the page.

### CODE REVIEW

**Comment by c00w** [comment]
I assume thisis public domain.

**Comment by hawks5999** [comment]
Everything I do for bitHopper project is public domain.

**Comment by c00w** [comment]
Yeah but I never remember.

**Comment by hawks5999** [comment]
It's cool. I just figured a blanket statement needed to be made somewhere.

**Pull request merged**
