### PR TITLE
Global default socket timeout of 15 minutes for all modules that use sockets

### PR DESCRIPTION
**Pull request by sdogi**
public domain

### CODE REVIEW

**Comment by sdogi** [comment]
Made web interface "Show disabled pools" checkbox not checked by default. Since disabled pools don't actually get used for anything it's best not to make them add clutter.

**Comment by sdogi** [comment]
All public domain as always

**Comment by c00w** [comment]
Can't you just do socket.settimeout once in the main package? Or does it have to be in every package?

**Comment by sdogi** [comment]
Yeah it has to be in every package. Tested it both ways.

Wanted to attach it to bithopper class but I figure with current approach it is the best. Because when we import more modules in the future that use sockets it may get too complicated(we might miss applying it to new modules).

The reason appears to be that when you import module then socket timeout gets set to None again. This also means that socket.setdefaulttimeout() has to be after the module gets imported.

**Pull request merged**
