### PR TITLE
My first git pull request!

### PR DESCRIPTION
**Pull request by xzion**
Hi c00w,

Giving this a go for the first time since I made some changes I thought were helpful. Since BTCG now uses live stats (p153 of their bitcointalk thread) I changed the API to scrape the homepage stats. Works like a charm, preferred mining role should now be role: mine

Added Masterpool.eu as a Namecoin pool so I could mine it for low Namecoin rounds as well as bitcoin rounds. Still waiting on someone to do the math on that and see whether or not it comes out as better profit than mining PPS, but I thought it would be good to add anyway! 

Hopefully I haven't stuffed anything up!

Cheers.

### CODE REVIEW

**Comment by c00w** [comment]
Is it in the public domain/ transfer copyright to me?

**Comment by xzion** [comment]
not sure what you're talking about sorry.

if you mean do I want the changes to be freely available then yes, of course!

**Comment by xzion** [comment]
had a chat to para, bit better understanding now, yes it is in the public domain.

**Comment by xzion** [comment]
shit, that was clearly the wrong button

**Pull request merged**
