### PR TITLE
Fixes to AltSliceScheduler

### PR DESCRIPTION
**Pull request by echiu64**
Tested for many rounds using a real miner. Now consistently slices by %shares of all hoppable pool shares. Added minimum slicing duration for pools that recently found a block would skew the time slice almost entirely in its favour.

### CODE REVIEW

**Comment by c00w** [comment]
Public domain or transfer copyright to me?

**Comment by c00w** [comment]
I assume I should close the other one as well.

**Comment by echiu64** [comment]
Yes public domain

**Comment by echiu64** [comment]
Please pull the latest fix (6e7409b7372e3cc8a4f1), it weights based on least # of shares vs most # of shares (oops)

**Comment by echiu64** [comment]
Will send a more up to date pull req

**Pull request closed without merging**
