### PR TITLE
Splitting user specific configs to own file

### PR DESCRIPTION
**Pull request by MarkusTeufelberger**
This submitted code is public domain.

I hope it somehow works to be merged, first time trying out github + Git..

pools.cfg now contains only data like API parsing + links, user.cfg.default defaults to info for hoppable pools, backup for PPS and disable for all others and contains a few explanations.

In pool.py the parser reads first user.cfg, as it might need some API keys to combine into links (not sure if it's smart enough if done the other way round). Haven't tested the case with only one file empty yet (meaning not much useful data in the pools dictionary).

### CODE REVIEW

**Comment by c00w** [comment]
Um, merge from trunk and then resubmit. I already fixed the pool.py issues with gnaget trying to fix api_disable without telling me.

I want all pools to start as mine if they can be mined. bitclockers should be in the mine list. 

mine_namecoins is mine_nmc.

If you don't want to change that I can do it myself but it'll have to wait for me to have the time to merge + fix.

see http://help.github.com/send-pull-requests/ for help with merging changes.

**Comment by c00w** [comment]
Oh and do you either transfer the copyright to me or release it into the public domain?

EDIT: nvm. Didn't see the release earlier.

**Comment by c00w** [comment]
Oh and you need to add a url field from the latest pool.cfg.default or else the website will break.

**Comment by MarkusTeufelberger** [comment]
Alright, I'll do the changes and try to merge with trunk.

**Comment by c00w** [comment]
Sweet. This will be very useful.
And you should update the readme.

**Comment by MarkusTeufelberger** [comment]
Phew, was a bit of work to get it going the first time, but merging works like a charm! <3 git already! :D
I'll update the readme.

**Comment by c00w** [comment]
Sweet. And once you get that done I'll merge it in. Thanks for doing this.

**Comment by MarkusTeufelberger** [comment]
Actually it should already be there...?! Weird, it shows up in my master... - maybe because I closed the request? I'll push a pseudo - commit, maybe that helps.

**Comment by MarkusTeufelberger** [comment]
Yeah, that was it! :-)
It was just an annoying enough issue to rectify the 30 minutes of coding/copy-pasting...

**Pull request merged**
