### PR TITLE
Check if POST request is LP request and respond accordingly.

### PR DESCRIPTION
**Pull request by mykohsu**
Check if POST request is LP request and respond accordingly. Fixes cgminer, and likely other POST /LP miners. These miners are calling /LP on the wrong connection.

### CODE REVIEW

**Comment by c00w** [comment]
Um Public Domain or transfer the copyright to me? And if lp is requested see line 156-157
`if name == 'LP':
                return lpSite(self.bitHopper)`

**Comment by c00w** [comment]
Has cgminer or diablo miner not been working for you? I'm checking now for myself.

**Comment by c00w** [comment]
It appears to be working for me.

**Comment by MarkusTeufelberger** [comment]
I'm mining with cgminer without issues too...

**Comment by c00w** [comment]
I'm going to close this pull request. If you have a miner with an issue tell me and I'll take another look.

**Comment by mykohsu** [comment]
Which version of cgminer are you using? 1.5.x removed GET LP and went back to POST LP. I haven't been using the latest bitHopper so I don't know if this one is working. I guess I can download it and run it and see, but for the bitHopper from about 1 week ago it is not working.

```
def render_POST(self, request):
    strReq = str(request)

    if strReq.find("/LP") >=0:
        bithopper_global.new_server.addCallback(bitHopperLP, (request))
        return server.NOT_DONE_YET
    else:
        return bitHopper_Post(request)

def getChild(self,name,request):
    if name == 'LP':
        return lpSite()
    return self
```

Btw, the version I'm running also has if name == 'LP' and it definitely does not work.

**Comment by mykohsu** [comment]
Should have tried the new code first :) Cgminer is working for me with the current git. I don't know how twisted works to know what the fix was, but the old code does not get called on getChild and rather goes straight to render_POST.

**Comment by mykohsu** [comment]
Still broken:

[2011-08-01 11:34:47] Accepted 2f18bd00 GPU 0 thread 2
[2011-08-01 11:35:41] Rejected c8612138 GPU 0 thread 2
[2011-08-01 11:35:42] Rejected 59fd0a2f GPU 0 thread 2
[2011-08-01 11:35:48] Rejected 08b6ab0c GPU 0 thread 1
[2011-08-01 11:35:49] Rejected 930aeb11 GPU 0 thread 1
[2011-08-01 11:35:49] LONGPOLL detected new block on network, waiting on fresh w
ork
[2011-08-01 11:36:26] Accepted 094ddecb GPU 0 thread 0
[2011-08-01 11:36:31] Accepted 50160fe6 GPU 0 thread 1

[2011-08-01 11:41:33] Accepted 4fcb94e1 GPU 0 thread 1
[2011-08-01 11:41:43] Accepted 6394fc1b GPU 0 thread 1
[2011-08-01 11:41:55] Accepted f4d170ac GPU 0 thread 0
[2011-08-01 11:42:09] New block detected on network before longpoll, waiting on
fresh work
[2011-08-01 11:42:14] Accepted cfe8440f GPU 0 thread 2

[2011-08-01 11:45:10] Accepted 3d5b0839 GPU 0 thread 0
[2011-08-01 11:45:10] Accepted 2e5fcc30 GPU 0 thread 1
[2011-08-01 11:45:34] longpoll failed, sleeping for 30s
[2011-08-01 11:45:50] Rejected 1d2ac423 GPU 0 thread 2
[2011-08-01 11:46:03] LONGPOLL detected new block on network, waiting on fresh w
ork
[2011-08-01 11:46:05] LONGPOLL detected new block on network, waiting on fresh w
ork

**Pull request closed without merging**
